const Items = 

 [
        {
            "author": "Michael Gleeson",
            "title": "The Old Xavs boy without an enemy in the game: Who is new AFL boss Andrew Dillon?",
            "description": "Andrew Dillon comes from a family of lawyers, footballers and priests. What type of CEO will he be?",
            "url": "https://www.brisbanetimes.com.au/sport/afl/the-old-xavs-boy-without-an-enemy-in-the-game-who-is-new-afl-boss-andrew-dillon-20230412-p5czux.html?ref=rss&utm_medium=rss&utm_source=rss_sport_afl",
            "source": "brisbanetimes",
            "image": "https://static.ffx.io/images/$zoom_0.3%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_442%2C$y_3/t_crop_custom/q_86%2Cf_jpg/0087f0f7469a12a498d3f30374ae07d70efbba69",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:10:01+00:00"
        },
        {
            "author": "Michael Gleeson",
            "title": "The Old Xavs boy without an enemy in the game: Who is new AFL boss Andrew Dillon?",
            "description": "Andrew Dillon comes from a family of lawyers, footballers and priests. What type of CEO will he be?",
            "url": "https://www.brisbanetimes.com.au/sport/afl/the-old-xavs-boy-without-an-enemy-in-the-game-who-is-new-afl-boss-andrew-dillon-20230412-p5czux.html?ref=rss&utm_medium=rss&utm_source=rss_sport",
            "source": "brisbanetimes",
            "image": "https://static.ffx.io/images/$zoom_0.3%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_442%2C$y_3/t_crop_custom/q_86%2Cf_jpg/0087f0f7469a12a498d3f30374ae07d70efbba69",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:10:01+00:00"
        },
        {
            "author": "Caryl Shepard, Reporter",
            "title": "NU indie alternative rock band safety scissors sets sights high following successful first gigs",
            "description": "After attracting a large audience at its first few Evanston shows, the indie alternative rock band safety scissors looks to expand its presence at Northwestern.&#160; The quartet comprises Communication junior Judy Lawrence on guitar, Weinberg sophomore Anika Wilsnack on drums, McCormick junior Maddie Farr on vocals and guitar, and Weinberg junior Hope McKnight on bass.&#160;...The post NU indie alternative rock band safety scissors sets sights high following successful first gigs appeared first on The Daily Northwestern.",
            "url": "https://dailynorthwestern.com/2023/04/30/ae/nu-indie-alternative-rock-band-safety-scissors-sets-sights-high-following-successful-first-gigs/",
            "source": "dailynorthwestern",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:04:17+00:00"
        },
        {
            "author": "-",
            "title": "Louis Vuitton turns Seoul bridge into massive runway",
            "description": "Louis Vuitton transformed a bridge spanning the Han River into a massive runway for its latest collection this weekend. Models strutted down the Jamsugyo Bridge to music to showcase the luxury fashion house’s pre-fall collection that included sunglasses, chunky black-and-white loafers and sandals as well as an assortment of large, colorful bags and smaller ones [&#8230;]The post Louis Vuitton turns Seoul bridge into massive runway appeared first on MACAU DAILY TIMES 澳門每日時報.",
            "url": "https://macaudailytimes.com.mo/louis-vuitton-turns-seoul-bridge-into-massive-runway.html?utm_source=rss&utm_medium=rss&utm_campaign=louis-vuitton-turns-seoul-bridge-into-massive-runway",
            "source": "macaudailytimes",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "mo",
            "published_at": "2023-05-01T00:04:48+00:00"
        },
        {
            "author": "",
            "title": "Travel hot list, May 2023: The top new hotels and attractions",
            "description": "Singapore’s amazing new hotel, the glamping resort favoured by Princess Di and two spectacular Australian light installations are among this month’s highlights.",
            "url": "https://www.smh.com.au/traveller/inspiration/travel-hot-list-may-2023-the-top-new-hotels-and-attractions-20230424-p5d2x0.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$zoom_0.275%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_63/t_crop_custom/q_86%2Cf_jpg/87d6bb6dff7577f41b619357dbd04acf1eab5139",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:07:59+00:00"
        },
        {
            "author": "Angus Dalton",
            "title": "‘Had to see it with my own eyes’: Crocodile found in suburban backyard",
            "description": "A crocodile that was likely an illegal pet set free was discovered roaming the suburbs.",
            "url": "https://www.smh.com.au/national/nsw/had-to-see-it-with-my-own-eyes-crocodile-found-in-suburban-backyard-20230501-p5d4ie.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$zoom_0.38074834013278935%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_100%2C$y_109/t_crop_custom/q_86%2Cf_jpg/1415ba4c4304f058cd030388b52d0d1257be4b09",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:00:43+00:00"
        },
        {
            "author": "Adam Kurkjian",
            "title": "A Shot For Life: First football event scores",
            "description": "NEEDHAM — At St. Sebastian&#8217;s for Sunday&#8217;s A Shot For Life Bowl, the organization&#8217;s first football event, it was cold, and it was wet. But it was also fun. Lots, and lots of fun. That was the main takeaway for both event organizers and players who took part in the four-team 7-on-7 tournament. Sure, the [&#8230;]",
            "url": "https://www.bostonherald.com/2023/04/30/a-shot-for-life-first-football-event-scores/",
            "source": "bostonherald",
            "image": "https://www.bostonherald.com/wp-content/uploads/2023/04/043023-footballcc02.jpg?w=1400px&strip=all",
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:03:10+00:00"
        },
        {
            "author": "Marian Bouchot",
            "title": "CHP issues Silver Alert for a 78-year-old man",
            "description": "The California Highway Patrol has issued a Silver Alert for 78-year-old Salvador Gutierrez. He was last seen around 7 p.m. Saturday in Coachella. He is 5 foot 6, 175 pounds with gray hair and brown eyes. Gutierrez is believed to be walking wearing a red shirt, tan pants, and brown shoes. If you see him, youThe post CHP issues Silver Alert for a 78-year-old man appeared first on KESQ.",
            "url": "https://kesq.com/top-stories/2023/04/30/chp-issues-silver-alert-for-a-78-year-old-man/",
            "source": "kesq",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:09:51+00:00"
        },
        {
            "author": "AP News",
            "title": "Padres rally for 2-game Mexican sweep, beat Giants 6-4",
            "description": "Matt Carpenter capped an eighth-inning rally with a tiebreaking, two-run double off the glove of diving centerfielder Mike Yastrzemski, and the San Diego Padres beat the San Francisco Giants 6-4 for a two-game sweep of Major League Baseball’s first regular-season series in Mexico City",
            "url": "https://www.mymotherlode.com/sports/baseball-game-stories/3069266/padres-rally-for-2-game-mexican-sweep-beat-giants-6-4.html",
            "source": "mymotherlode",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:05:04+00:00"
        },
        {
            "author": "Nathan Jolly",
            "title": "Best & Less Takeover Looks Likely",
            "description": "Best & Less&#8217; largest shareholder is likely to accept a $1.89 a share takeover bid for the retailer. The proposal, made by retail investor Brett Blundy and iRetail owner Ray Itaoui, is 4.5 per cent lower than the $1.99 closing price for the company &#8212; and considerably less than its IPO first-day closing price of... Read More",
            "url": "https://www.channelnews.com.au/best-less-takeover-looks-likely/",
            "source": "channelnews",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:03:12+00:00"
        },
        {
            "author": "Jacquelin Magnay",
            "title": "From the Archives, 1998: Susie O’Neill swims into the history books",
            "description": "In 1998, Susan O’Neill received a standing ovation and thunderous applause when she became the most prolific Australian titleholder in swimming history at a packed Melbourne Aquatic Centre.",
            "url": "https://www.watoday.com.au/sport/swimming/from-the-archives-1998-susie-o-neill-swims-into-the-history-books-20230427-p5d3tq.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "watoday",
            "image": "https://static.ffx.io/images/$zoom_0.3711%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_jpg/fe90c68d366cd960ec093b26ed73feee979b54e9",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:00:00+00:00"
        },
        {
            "author": "Cointelegraph",
            "title": "Fed, NYDFS assess their supervisory performance after March’s big bank failures",
            "description": "Fed, NYDFS assess their supervisory performance after March’s big bank failures",
            "url": "https://www.investing.com/news/cryptocurrency-news/fed-nydfs-assess-their-supervisory-performance-after-marchs-big-bank-failures-3068577",
            "source": "Investing.com | Stock Market Quotes &amp; Financial News",
            "image": "https://i-invdn-com.investing.com/news/LYNXNPEE1J1IK_M.jpg",
            "category": "business",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:00:13+00:00"
        },
        {
            "author": "Angus Dalton",
            "title": "‘Had to see it with my own eyes’: Crocodile found in suburban backyard",
            "description": "A crocodile that was likely an illegal pet set free was discovered roaming the suburbs.",
            "url": "https://www.smh.com.au/national/nsw/had-to-see-it-with-my-own-eyes-crocodile-found-in-suburban-backyard-20230501-p5d4ie.html?ref=rss&utm_medium=rss&utm_source=rss_national_nsw",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$zoom_0.38074834013278935%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_100%2C$y_109/t_crop_custom/q_86%2Cf_jpg/1415ba4c4304f058cd030388b52d0d1257be4b09",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:00:43+00:00"
        },
        {
            "author": "lyndon",
            "title": "Gordon Campbell on the politics of “greedflation”",
            "description": "Even though inflation has peaked – it fell to 6.7% last week – we are still being told to expect high interest rates to persist [...]",
            "url": "http://werewolf.co.nz/2023/05/gordon-campbell-on-the-politics-of-greedflation/",
            "source": "gordoncampbell",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "nz",
            "published_at": "2023-05-01T00:00:05+00:00"
        },
        {
            "author": "Jacquelin Magnay",
            "title": "From the Archives, 1998: Susie O’Neill swims into the history books",
            "description": "In 1998, Susan O’Neill received a standing ovation and thunderous applause when she became the most prolific Australian titleholder in swimming history at a packed Melbourne Aquatic Centre.",
            "url": "https://www.brisbanetimes.com.au/sport/swimming/from-the-archives-1998-susie-o-neill-swims-into-the-history-books-20230427-p5d3tq.html?ref=rss&utm_medium=rss&utm_source=rss_sport",
            "source": "brisbanetimes",
            "image": "https://static.ffx.io/images/$zoom_0.3711%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_jpg/fe90c68d366cd960ec093b26ed73feee979b54e9",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:00:00+00:00"
        },
        {
            "author": "Thuc Nhi Nguyen",
            "title": "School is in session as Sparks begin training camp",
            "description": "The Sparks opened training camp Sunday with a new coach and executive group plus plenty of questions about their potential and the learning curve.",
            "url": "https://www.latimes.com/sports/sparks/story/2023-04-30/sparks-open-training-camp-with-plenty-to-learn",
            "source": "latimes",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:01:42+00:00"
        },
        {
            "author": "Brittny Mejia",
            "title": "Man found guilty of murdering teens who 'ding-dong-ditched' his house",
            "description": "Anurag Chandra was convicted of three counts of first-degree murder and three counts of attempted murder after forcing a car full of teens off the road.",
            "url": "https://www.latimes.com/california/story/2023-04-30/anurag-chandra-murder-teens-ding-dong-ditch",
            "source": "latimes",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:01:23+00:00"
        },
        {
            "author": "A. Joseph Dial, Purdue University",
            "title": "The Film ‘Air’ Isn’t Actually About Michael Jordan At All",
            "description": "The film “Air,” which tells the story of Nike’s signing of Michael Jordan, isn’t actually about Michael Jordan at all.",
            "url": "https://newsone.com/4571143/the-film-air-isnt-actually-about-michael-jordan-at-all/",
            "source": "newsone",
            "image": "https://newsone.com/wp-content/uploads/sites/22/2023/04/16828543702541.jpg?quality=80&strip=all&w=560&crop=0,0,100,320px",
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:00:43+00:00"
        },
        {
            "author": "Deborah Sullivan Brennan",
            "title": "Should Nathan Fletcher's replacement be appointed or elected? Supervisors weigh expediency versus accountability",
            "description": "Appointing a successor to the disgraced supervisor would be quicker, but a special election would give voters greater voice, candidates and voting-rights advocates say.",
            "url": "https://www.sandiegouniontribune.com/news/politics/story/2023-04-30/nathan-fletcher-replacement-district-4-appointed-or-elected",
            "source": "nctimes",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:00:50+00:00"
        },
        {
            "author": "Olivia Stringer",
            "title": "Emmerdale spoilers for May 1, 2023: Suzy becomes suspicious of Faye and Arthur and Marshall agree to go on a date",
            "description": "Suzy has seen though Faye's facade",
            "url": "https://metro.co.uk/2023/05/01/emmerdale-spoilers-for-may-1-2023-suzy-becomes-suspicious-of-faye-18697740/",
            "source": "Metro",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "gb",
            "published_at": "2023-05-01T00:00:00+00:00"
        },
        {
            "author": "Jacquelin Magnay",
            "title": "From the Archives, 1998: Susie O’Neill swims into the history books",
            "description": "In 1998, Susan O’Neill received a standing ovation and thunderous applause when she became the most prolific Australian titleholder in swimming history at a packed Melbourne Aquatic Centre.",
            "url": "https://www.smh.com.au/sport/swimming/from-the-archives-1998-susie-o-neill-swims-into-the-history-books-20230427-p5d3tq.html?ref=rss&utm_medium=rss&utm_source=rss_sport",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$zoom_0.3711%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_jpg/fe90c68d366cd960ec093b26ed73feee979b54e9",
            "category": "sports",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:00:00+00:00"
        },
        {
            "author": "Jacquelin Magnay",
            "title": "From the Archives, 1998: Susie O’Neill swims into the history books",
            "description": "In 1998, Susan O’Neill received a standing ovation and thunderous applause when she became the most prolific Australian titleholder in swimming history at a packed Melbourne Aquatic Centre.",
            "url": "https://www.theage.com.au/sport/swimming/from-the-archives-1998-susie-o-neill-swims-into-the-history-books-20230427-p5d3tq.html?ref=rss&utm_medium=rss&utm_source=rss_sport",
            "source": "The Age",
            "image": "https://static.ffx.io/images/$zoom_0.3711%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_jpg/fe90c68d366cd960ec093b26ed73feee979b54e9",
            "category": "sports",
            "language": "en",
            "country": "au",
            "published_at": "2023-05-01T00:00:00+00:00"
        },
        {
            "author": "-",
            "title": "Emergency aid supplies reach Sudan, as fighting sputters on",
            "description": "An aircraft carrying eight tons of emergency medical aid landed Sunday in Sudan to resupply hospitals devastated by more than two weeks of fighting between forces loyal to rival generals. The supplies are enough to treat hundreds of wounded, as the civilian death toll from the countrywide violence topped 400. The conflict erupted on April [&#8230;]The post Emergency aid supplies reach Sudan, as fighting sputters on appeared first on MACAU DAILY TIMES 澳門每日時報.",
            "url": "https://macaudailytimes.com.mo/emergency-aid-supplies-reach-sudan-as-fighting-sputters-on.html?utm_source=rss&utm_medium=rss&utm_campaign=emergency-aid-supplies-reach-sudan-as-fighting-sputters-on",
            "source": "macaudailytimes",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "mo",
            "published_at": "2023-05-01T00:14:48+00:00"
        },
        {
            "author": "-",
            "title": "Canada makes new contract offer to striking public workers",
            "description": "Canada’s government made a new contract offer to the country’s biggest public workers union Friday as thousands of federal employees remained on strike for a 10th day. The office of Treasury Board President Mona Fortier called it a &#8220;comprehensive offer” but provided no details. The Public Service Alliance of Canada, which had said Wednesday that [&#8230;]The post Canada makes new contract offer to striking public workers appeared first on MACAU DAILY TIMES 澳門每日時報.",
            "url": "https://macaudailytimes.com.mo/canada-makes-new-contract-offer-to-striking-public-workers.html?utm_source=rss&utm_medium=rss&utm_campaign=canada-makes-new-contract-offer-to-striking-public-workers",
            "source": "macaudailytimes",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "mo",
            "published_at": "2023-05-01T00:12:44+00:00"
        },
        {
            "author": "Seaman Apprentice Pierce Luck",
            "title": "Daily Operations Aboard USS George H.W. Bush (CVN 77) [Image 5 of 10]",
            "description": "230427-N-SK738-1116 NORFOLK, Va. (April 27, 2023) Aviation Boatswain’s Mate (Handling) 2nd Class Olalekan Oluwagbamila, assigned to the Nimitz-class aircraft carrier USS George H.W. Bush (CVN 77), smiles beside a dog from the USO Canine Comfort event, April 27, 2023. The George H.W. Bush Carrier Strike Group is an integrated combat weapons system that delivers superior combat capability to deter, and if necessary, defeat America's adversaries in support of national security.(Navy photo by Mass Communication Specialist Seaman Apprentice Pierce Luck)",
            "url": "https://www.dvidshub.net/image/7769890/daily-operations-aboard-uss-george-hw-bush-cvn-77",
            "source": "dvidshub",
            "image": "https://cdn.dvidshub.net/media/thumbs/photos/2304/7769890/179x250_q75.jpg",
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2023-05-01T00:10:48+00:00"
        }
    ]


    export default Items;